export enum FieldType {
    Text = "Text",
    Date = "Date",
    Number = "Number",
    Checkbox = "Checkbox",
    Email = "Email",
    DropDown = "DropDown",
    Radio = "Radio"
}
export enum SearchResultFieldMapping {
    MovieName = "movie_name_t",
    SHOWTIMEDATE = "show_date_dt",
    SHOWTIMES = "showtimes_ts",
    SHOWTIMEMINUTES = "showtime_minutes_is",
    SHOWPASSES = "show_passes_t",
    SHOWFESTIVAL = "show_festival_t",
    SHOWCOMMENTS = "show_comments_ts",
    TITLE = "title_t",
    GENRES = "genres_ts",
    PICTURES = "pictures_ts",
    RATING = "rating_t",
    ADVISORY = "advisory_t",
    CAST = "casts_ts",
    DIRECTORS = "directors_ts",
    RELEASEDATE = "release_date_dt",
    RELEASENOTE = "release_notes_t", 
    RUNNINGTIME = "running_time_i", 
    DISTRIBUTORS = "distributors_ts", 
    WRITERS = "writers_ts", 
    SYNOPSIS = "synopsis_t", 
    LANGUAGE = "lang_t", 
    INITIALNAME = "intl_name_t", 
    INITIALCOUNTRY = "intl_country_t", 
    INITIALCERT = "intl_cert_t", 
    INITIALRELEASEDATE = "intl_release_dt", 
    THEATERNAME = "theater_name_t", 
    THEATERADDRESS = "theater_address_t",
    THEATERCITY = "theater_city_t",  
    THEATERSTATE = "theater_state_t", 
    THEATERZIP = "theater_zip_t", 
    THEATERPHONE = "theater_phone_t", 
    THEATERTICKTING = "theater_ticketing_t", 
    THEATERLOCATION = "theater_location_t",
    THEATERSCREENS = "theater_screens_i",
    THEATERCOUNTRY = "theater_country_t",
    THEATERURL = "theater_url_t"
}